apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-part2
  labels:
    app: project-part2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-part2
  template:
    metadata:
      labels:
        app: project-part2
    spec:
      containers:
      - name: project-part2
        image: project-part2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: project-part2-service
spec:
  selector:
    app: project-part2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
